[package]
name = "brewy"
version = "0.1.0"
edition = "2024"
description = "A fast terminal interface for Homebrew"
license = "MIT"
repository = "https://github.com/Hexadecimall/homebrew-brewy"
homepage = "https://github.com/Hexadecimall/homebrew-brewy"
readme = "README.md"
rust-version = "1.88"
keywords = ["homebrew", "tui", "macos", "terminal"]
categories = ["command-line-utilities"]
exclude = ["code", "fanctl_fix/**"]

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm_0_29"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"

[profile.release]
lto = "thin"
strip = true
